project:
  type: website
  render:
    - /slides/index.qmd

title:  An end-to-end architecture for enhancing reproducibility in nowcasting
author:
    - name: "**[Thomas Faria]{.blue2}**"
      # email: thomas.faria@insee.fr
      # affiliations:
      #   - name: "[__Insee__]{.orange}"

date: 03/12/2025
date-format: "11/03/2025"
slide-number: true
footer: |
# uncomment for French presentations:
#lang: fr-FR
# for blind readers:
slide-tone: false
# for @olevitt:
chalkboard: # press the B key to toggle chalkboard
  theme: whiteboard
# uncomment to use the multiplex mode:
#multiplex: true
format:
  # pick the light mode (onyxia-revealjs) or the dark mode (onyxia-dark-revealjs)
  onyxia-revealjs:
  #onyxia-dark-revealjs:
    output-file: index.html
    incremental: false
controls: true
css: custom.css
from: markdown+emoji
